# Server
server.port=8080

# Spring application
spring.application.name=forum-backend

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/forumIT
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration for Render
spring.data.redis.host=rediss://red-d649cnnfte5s7381vl4g:HWZMngZC2W4Z45dhxAgt3GoMdWtnm8Ot@oregon-keyvalue.render.com:6379
spring.data.redis.port=6379
spring.data.redis.username=red-admin
spring.data.redis.password=HWZMngZC2W4Z45dhxAgt3GoMdWtnm8Ot

# BẮT BUỘC: Bật SSL để kết nối external tới Render
spring.data.redis.ssl.enabled=true

# JWT
jwt.secret=9a4f2c8d3b7a1e5f2g8h4i0j7k2l5m8n1o4p7q0r3s6t9u2v5w8x1y4z7a0b3c6d
jwt.expiration=3600000